# Site settings
title: CBusJS
description: "Columbus JavaScript Usergroup"
url: http://columbusjs.org
email: guy@guyroyse.com
twitter_username: cbusjs
github_username:  cbusjs
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sass-converter
  - kramdown
  - rouge
markdown: kramdown
highlighter: rouge
timezone: America/Detroit
safe: false
paginate: 3
permalink: /:month-:day-:year/:title.html
future: true
